version: 1.0.{build}
image: Visual Studio 2022
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
environment:
  APPVEYOR_RDP_PASSWORD: Zoom@7878
build:
  verbosity: minimal
